site_name: Test Docs Site
repo_url: 'https://github.com/chi-initiative/kora-documentation'
extra_css:
    - css/extra.css

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - 'Home': 'index.md'
    - 'Searching': 'search.md'
    - 'Getting Started': 
        - 'Understanding Core Concepts': 'getting-started/core-concepts.md'
    - 'Projects':
        - 'Creating a Project': 'projects/create-project.md'
    - 'Forms':
        - 'Creating a Form': 'forms/create-form.md'
    - 'Records':
        - 'Creating a Record': 'records/create-record.md'
    - 'User & Account Management':
        - 'Adding Users to Projects': 'user-accounts/add-user.md'
    - 'Managing a Kora Installation':
        - 'Updating a Kora 3 Installation': 'management/update-kora.md'
