site_name: Kora 3 User Documentation
repo_url: 'https://github.com/chi-initiative/kora-documentation'
extra_css:
    - css/extra.css

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - 'Home': 'index.md'
  #  - 'Searching': 'search.md'
    - 'Getting Started':
        - 'System Requirements': 'getting-started/system_requirements.md'
        - "Installing Kora on Domain of One's Own & Reclaim Hosting": 'getting-started/installing_kora_domains.md'
        - 'Understanding Core Concepts': 'getting-started/core-concepts.md'
        - 'Searching and Browsing in Kora': 'getting-started/searching_and_browsing.md'
        - 'Working with the Dashboard': 'getting-started/working_with_the_dashboard.md'
    - 'Projects':
        - 'Creating a Project': 'projects/creating_a_project.md'
        - 'Adding Users to Projects': 'projects/adding_users_to_projects.md'
        - 'Exporting a Project': 'projects/exporting_a_project.md'
        - 'Importing a Project': 'projects/importing_a_project.md'
        - 'Archiving a Project': 'projects/archiving_a_project.md'
        - 'Customizing your Project View': 'projects/customizing_your_project_view.md'
        - 'Customizing Project List View': 'projects/customizing_project_list_view.md'
        - 'Deleting a Project': 'projects/deleting_a_project.md'
        - 'Accessing and Managing Projects from the Dashboard': 'projects/accessing_and_managing_projects_from_the_dashboard.md'
        - 'Editing a Project': 'projects/editing_a_project.md'
    - 'Forms':
        - 'Creating a Form': 'forms/creating_a_form.md'
        - 'Understanding Field Types': 'forms/understanding_field_types.md'
        - 'Batch Assigning Field Values': 'forms/batch_assigning_field_values.md'
        - 'Adding Users to a Form': 'forms/adding_users_to_forms.md'
        - 'Adding Additional Form Administrators': 'forms/additional_form_administrators.md'
        - 'Creating a Multipage Form': 'forms/creating_a_multipage_form.md'
        - 'Creating Fields': 'forms/creating_fields.md'
        - 'Editing a Form': 'forms/editing_a_form.md'
        - 'Editing Fields': 'forms/editing_fields.md'
        - 'Exporting a Form': 'forms/exporting_a_form.md'
        - 'Navigating to a Form': 'forms/navigating_to_a_form.md'
        - 'Importing a Form': 'forms/importing_a_form.md'
        - 'Using Field Value Presets': 'forms/field_value_presets.md'
    - 'Records':
        - 'Creating a Record': 'records/creating_a_record.md'
        - 'Viewing and Managing Record Revisions': 'records/viewing_and_managing_record_revisions.md'
        - 'Importing a Record': 'records/importing_a_record.md'
        - 'Importing Multiform Records': 'records/importing_multi_form_records.md'
        - 'Using Record Presets': 'records/using_record_presets.md'
        - 'Searching and Browsing Records': 'records/searching_and_browsing_records.md'
        - 'Editing a Record': 'records/editing_a_record.md'
        - 'Exporting a Record': 'records/exporting_a_record.md'
    - 'User & Account Management':
        - 'Viewing your User Account': 'user-accounts/viewing_your_user_account.md'
        - 'Viewing Your Project Permissions': 'user-accounts/view_your_project_permissions.md'
        - 'Understanding and Working with Permission Groups': 'user-accounts/understanding_and_working_with_permission_groups.md'
        - 'Editing User Preferences': 'user-accounts/edit_user_preferences.md'
        - 'Editing Your User Account': 'user-accounts/edit_user_account.md'
        - 'Customizing Your Project View': 'user-accounts/customizing_your_project_view.md'
        - 'Managing Users in a Kora Installation': 'user-accounts/managing_users_in_a_kora_installation.md'
        - 'Resetting your Kora Password': 'user-accounts/resetting_your_password.md'
        - 'Signing up for a User Account': 'user-accounts/signing_up_for_a_user_account.md'
    - 'Managing a Kora Installation':
        - 'Updating a Kora 3 Installation': 'management/update-kora.md'
        - 'Managing API Tokens': 'management/managing_api_tokens.md'
        - 'Editing Your Kora Installation Configuration': 'management/editing_your_kora_installation_configuration.md'
