site_name: Kora 3 User Manual
repo_url: 'https://github.com/chi-initiative/kora-documentation'
extra_css:
    - css/extra.css

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - 'Home': 'index.md'
  #  - 'Searching': 'search.md'
    - 'Getting Started':
        - 'System Requirements': 'getting-started/system_requirements.md'
        - 'Installing Kora': 'getting-started/installing_kora.md'
        - 'Understanding Core Concepts': 'getting-started/core-concepts.md'
        - 'Searching and Browsing in Kora': 'getting-started/searching_and_browsing.md'
        - 'Working with the Dashboard': 'getting-started/working_with_the_dashboard.md'
    - 'Projects':
        - 'Creating a Project': 'projects/creating_a_project.md'
        - 'Adding Users to Projects': 'projects/adding_users_to_projects.md'
        - 'Exporting a Project': 'projects/exporting_a_project.md'
        - 'Importing a Project': 'projects/importing_a_project.md'
        - 'Archiving a Project': 'projects/archiving_a_project.md'
    - 'Forms':
        - 'Creating a Form': 'forms/creating_a_form.md'
        - 'Understanding Field Types': 'forms/understanding _field_types.md'
        - 'Batch Assigning Field Values': 'forms/batch_assigning_field_values.md'
        - 'Adding Users to a Form': 'forms/adding_users_to_forms.md'
        - 'Adding Additional Form Administrators': 'forms/additional_form_administrators.md'
        - 'Creating a Multipage Form': 'forms/creating_a_multipage_form.md'
        - 'Creating Fields': 'forms/creating_fields.md'
        - 'Editing a Form': 'forms/editing_a_form.md'
        - 'Editing Fields': 'forms/editing_fields.md'
        - 'Exporting a Form': 'forms/exporting_a_form.md'
        - 'Navigating to a Form': 'forms/navigating_to_a_form.md'
        - 'Importing a Form': 'forms/importing_a_form.md'
    - 'Records':
        - 'Creating a Record': 'records/creating_a_record.md'
        - 'Viewing and Managing Record Revisions': 'records/viewing_and_managing_record_revisions.md'
        - 'Importing a Record': 'records/importing_a_record.md'
        - 'Using Record Presets': 'records/using_record_presets.md'
        - 'Searching and Browsing Records': 'records/searching_and_browsing_records.md'
        - 'Editing a Record': 'records/editing_a_record.md'
        - 'Exporting a Record': 'records/exporting_a_record.md'
    - 'User & Account Management':
        - 'Viewing Your Project Permissions': 'user-accounts/view_your_project_permissions.md'
        - 'Understanding and Working with Permission Groups': 'user-accounts/understanding_and_working_with_permission_groups.md'
        - 'Editing User Preferences': 'user-accounts/edit_user_preferences.md'
        - 'Editing Your User Account': 'user-accounts/edit_user_account.md'
    - 'Managing a Kora Installation':
        - 'Updating a Kora 3 Installation': 'management/update-kora.md'
